# Generated by Django 4.1.1 on 2022-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='text',
        ),
        migrations.AddField(
            model_name='userphoto',
            name='img',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
