# Generated by Django 4.1.1 on 2022-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_userphoto_galleria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to='images/{galleria}'),
        ),
    ]
