# Generated by Django 4.1.1 on 2022-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_remove_user_name_remove_userphoto_text_userphoto_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
