# Generated by Django 4.1.1 on 2022-09-19 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 19, 17, 41, 32, 976331, tzinfo=datetime.timezone.utc), verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userphoto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 19, 17, 41, 44, 441118, tzinfo=datetime.timezone.utc), verbose_name='date created'),
            preserve_default=False,
        ),
    ]
