# Generated by Django 4.1.1 on 2022-09-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_alter_userphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='galleria.usergallery')),
        ),
    ]
