# Generated by Django 4.1.1 on 2022-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0004_alter_userphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to='{galleria}/'),
        ),
    ]
