# Generated by Django 4.1.1 on 2022-09-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0004_user_date_userphoto_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleria.user'),
        ),
    ]
