# Generated by Django 4.1.1 on 2022-09-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0005_alter_usergallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='usergallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleria.usergallery'),
        ),
    ]
