# Generated by Django 4.1.1 on 2022-09-27 18:01

from django.db import migrations, models
import galleria.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0005_alter_userphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to=galleria.models.user_directory_path),
        ),
    ]
