# Generated by Django 4.1.1 on 2022-09-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0006_alter_userphoto_usergallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='img',
        ),
    ]
